[[redirects]]
  from = "/"
  to = "/index.html/"
  status = 200

[[redirects]]
  from = "/#/shop/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/#/cart/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/#/product/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404